---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/content.toml
  label: Content
- type: document
  path: data/appearance.toml
  label: Appearance
- type: document
  path: config.toml
  label: Configuration
upload_dir: content/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
