---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: CUSTOMIZING.md
  label: Help
  read_only: true
- type: document
  path: data/pageOptions.toml
  label: Customize
- type: document
  path: config.toml
  label: Site Config
upload_dir: content/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
